server:
  port: 8081
  
eureka:
  client:
    service-url:
     default-zone: http://localhost:8761/
     
spring:
#  datasource:
#   username: root
#   url: jdbc:mysql://localhost:3306/training
#   password: root
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    show-sql: true
#    hibernate:
#      ddl-auto: update
  application:
   name: MOB-SERVICE
  config:
    import: configserver:http://localhost:8888
  profiles:
    active: prod,dev